project:
  type: website
  output-dir: report

execute:
  freeze: auto

website:
  title: "Report"

  repo-url: https://github.com/break-through-cancer/btc-scrna-pipeline
  repo-branch: master
  repo-actions: [issue]

  sidebar:
    logo: logotype.jpeg
    pinned: true
    align: center

    contents:
      - href: index.qmd
        text: Introduction
      - auto: "step*.qmd"
      - href: references.qmd
        text: References
      - href: about.qmd
        text: About

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "nf-quarto"

format:
  html:
    toc: true
    fig-width: 8
    fig-height: 6
    code-tools: true
    default-image-extension: svg
    theme: litera
  ipynb: default

format-links: [ipynb]
